# Generated by Django 3.2.7 on 2021-09-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('numero', models.PositiveBigIntegerField(null=True, verbose_name='Número do Chamado')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Chamado')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('prioridade', models.CharField(choices=[('Média', 'Média'), ('Baixa', 'Baixa'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Baixa', max_length=60)),
                ('estado', models.CharField(choices=[('Aberto', 'Aberto'), ('Tratando', 'Tratando'), ('Fechado', 'Fechado'), ('Morto', 'Morto')], default='Aberto', max_length=60)),
                ('nota_de_fecho', models.CharField(max_length=200, null=True, verbose_name='Nota de Fecho')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.cliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.tecnico')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
