# Generated by Django 3.2.7 on 2021-09-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='nota_de_atribuicao',
            field=models.CharField(max_length=200, null=True, verbose_name='Nota de Atribuição'),
        ),
    ]
